---
- name: Copy gnome configuration override (wallpaper, favorites, date format and input sources).
  copy:
    src: "{{ role_path }}/files/gschema/30_ucr-gnome-settings.gschema.override"
    dest: /usr/share/glib-2.0/schemas
  tags:
    - desktop
    - execution
    - gnome

- name: initTest - Copied gnome configuration override.
  command: ls /usr/share/glib-2.0/schemas
  register: result
  failed_when: "'30_ucr-gnome' not in result.stdout"
  tags:
    - desktop
    - gnome
    - test
