---
- name: Display Packages Process Part Message.
  debug:
    msg:
      - 'INFO: Packages Configuration.'
  tags:
    - execution
    - packages
    - test

- name: Add deconf selections.
  debconf:
    name: "{{ item.debconf.name }}"
    question: "{{ item.debconf.question }}"
    value: 'true'
    vtype: select
  when: item.debconf is defined
  loop: "{{ packages }}"
  tags:
    - execution
    - packages

- name: unitTest - Add debconf selections.
  command: grep "oracle" /var/cache/debconf/config.dat
  register: result
  failed_when: "'oracle' not in result.stdout"
  tags:
    - packages
    - test

- name: Purge APT packages by name.
  apt:
    name: "{{ item.name }}"
    purge: true
    state: absent
  when: item.name is defined
  loop: "{{ purge_packages }}"
  tags:
    - execution
    - packages
    
- name: Purge APT packages without name.
  apt:
    name: "{{ item }}"
    purge: true
    state: absent
  when: item.name is defined
  loop: "{{ purge_packages }}"
  tags:
    - execution
    - packages

- name: Update APT packages cache
  apt:
    update_cache: yes
  tags:
    - execution
    - packages

# TODO: this is to slow, need to find another way
- name: Install APT packages by name.
  apt:
    name: "{{ item.name }}"
    state: latest
  when: (item.name is defined and item.arch is defined and item.arch == ansible_machine) or
        (item.name is defined and item.arch is not defined) 
  loop: "{{ packages }}"
  tags:
    - execution
    - packages

- name: Install APT packages without name.
  apt:
    name: "{{ item }}"
    state: latest
  when: item.name is not defined
  loop: "{{ packages }}"
  tags:
    - execution
    - packages

