---
- import_tasks: keys.yml

- name: Add repositories.
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ repositories }}"
  tags:
    - execution
    - repositories

- name: unitTest - Add repositories.
  command: ls /etc/apt/sources.list.d
  register: result
  failed_when: "'ppa_webupd8team_java_bionic.list' not in result.stdout"
  tags:
    - test
    - repositories

- import_tasks: unattended.yml
