---
- name: Enable unattended updates - distro.
  replace:
    path: "{{ unattended_file_path }}"
    regexp: '\/*(\s*)"\${distro_id}:\${distro_codename}-updates";'
    replace: '\1"${distro_id}:${distro_codename}-updates";'
  tags:
    - execution
    - repositories
    - unattended

- name: unitTest - enable unattended updates - distro.
  command: grep '"${distro_id}:${distro_codename}";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - repositories
    - test
    - unattended

- name: Enable unattended updates - minimal steps.
  replace:
    path: "{{ unattended_file_path }}"
    regexp: '\/*Unattended-Upgrade::MinimalSteps (.*);'
    replace: 'Unattended-Upgrade::MinimalSteps "true";'
  tags:
    - execution
    - repositories
    - unattended

- name: unitTest - enable unattended updates - minimal steps.
  command: grep 'Unattended-Upgrade::MinimalSteps "true";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - repositories
    - test
    - unattended

- name: Enable unattended updates - unused dependencies.
  replace:
    path: "{{ unattended_file_path }}"
    regexp: '\/*Unattended-Upgrade::Remove-Unused-Dependencies (.*);'
    replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
  tags:
    - execution
    - repositories
    - unattended

- name: unitTest - enable unattended updates - unused dependencies.
  command: grep 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - repositories
    - test
    - unattended

- name: Get repo name for APT unattended updates
  shell: >
    HTTP_REGEX='{{ http_regex }}';
    repo_name='{{ item.repo }}';
    [[ "$repo_name" =~ $HTTP_REGEX ]] && 
    repo_name=$(echo ${BASH_REMATCH[1]} | sed 's:/*$::' ) && 
    repo_release_info=$( apt-cache policy | grep -A 2 "$repo_name" | head -n 3 ) && 
    [[ "$repo_release_info" =~ o=(.*),a=(.*),n= ]] && 
    echo ${BASH_REMATCH[1]}:${BASH_REMATCH[2]}
  args:
    executable: /bin/bash
  when: item.repo is defined and item.repo | regex_search(http_regex)
  register: apt_repo_name
  loop: "{{ repositories }}"
  tags:
    - execution
    - repositories
    - unattended
    
- name: Add unattended update for APT
  lineinfile:
    path: "{{ unattended_file_path }}"
    insertafter: 'Unattended-Upgrade::Allowed-Origins {'
    line: '{{ item.stdout }};'
  when: item.stdout is defined
  loop: '{{ apt_repo_name.results }}'
  tags:
    - execution
    - repositories
    - unattended

- name: unitTest - Add unattended update for APT
  command: grep "{{item.stdout}}" {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  when: item.stdout is defined
  loop: '{{ apt_repo_name.results }}'
  tags:
    - repositories
    - test
    - unattended
