---
- import_tasks: plymouth.yml
- import_tasks: dconf.yml

- name: Copy mate configuration override.
  copy:
    src: "{{ role_path }}/files/gschema/30_ucr-mate-settings.gschema.override"
    dest: /usr/share/glib-2.0/schemas
  tags:
    - desktop
    - execution
    - mate

- name: initTest - Copied mate configuration override.
  command: ls /usr/share/glib-2.0/schemas
  register: result
  failed_when: "'30_ucr-mate' not in result.stdout"
  tags:
    - desktop
    - mate
    - test

- name: Compile mate gsettings override.
  command: glib-compile-schemas /usr/share/glib-2.0/schemas
  tags:
    - desktop
    - execution
    - mate

- name: unitTest - Compiled mate gsettings override.
  command: gsettings list-recursively org.mate.background
  register: result
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - desktop
    - mate
    - test

- name: Reset mate gsettings keys.
  command: bash -c 'gsettings list-schemas | xargs -n 1 gsettings reset-recursively'
  tags:
    - desktop
    - execution
    - mate

- name: unitTest - Resetted mate gsettings keys.
  command: bash -c "gsettings list-schemas | grep 'org.mate.sound'"
  register: result
  failed_when: result.stdout == ''
  tags:
    - desktop
    - mate
    - test
