---
- name:  Copy ubuntu-ucr plymouth themes to /usr/share/plymouth/themes.
  copy:
    src: "{{ role_path }}/files/plymouth/themes"
    dest: /usr/share/plymouth
  when: mate_xsession != ''
  tags:
    - execution
    - desktop
    - mate
    - plymouth

- name: unitTest - Copied ubuntu-ucr plymouth themes to /usr/share/plymouth/themes.
  command: ls /usr/share/plymouth/themes
  register: result
  when: mate_xsession != ''
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth

- name: Install default.plymouth alternative = ubuntu-ucr.
  alternatives:
    name: default.plymouth
    link: /usr/share/plymouth/themes/default.plymouth
    path: /usr/share/plymouth/themes/ubuntu-ucr/ubuntu-ucr.plymouth
    priority: 100
  tags:
    - execution
    - desktop
    - mate
    - plymouth

- name: unitTest - Installed alternative default.plymouth = ubuntu-ucr.
  command: update-alternatives --list default.plymouth
  register: result
  when: mate_xsession != ''
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth

- name: unitTest - Setted alternative default.plymouth = ubuntu-ucr.
  command: update-alternatives --display default.plymouth
  register: result
  when: mate_xsession != ''
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth

- name: Install text.plymouth alternative = ubuntu-ucr-text.
  alternatives:
    name: text.plymouth
    link: /usr/share/plymouth/themes/text.plymouth
    path: /usr/share/plymouth/themes/ubuntu-ucr-text/ubuntu-ucr-text.plymouth
    priority: 100
  when: mate_xsession != ''
  tags:
    - execution
    - desktop
    - mate
    - plymouth

- name: unitTest - Installed alternative text.plymouth = ubuntu-ucr.
  command: update-alternatives --list text.plymouth
  register: result
  when: mate_xsession != ''
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth

- name: unitTest - Setted alternative text.plymouth = ubuntu-ucr.
  command: update-alternatives --display text.plymouth
  register: result
  when: mate_xsession != ''
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth

- name: Copy ubuntu-ucr-text.so to /usr/lib/{{ ansible_architecture }}-linux-gnu/plymouth.
  copy:
    src: "{{ role_path }}/files/plymouth/ubuntu-ucr-text.so"
    dest: "/usr/lib/{{ ansible_architecture }}-linux-gnu/plymouth"
  when: mate_xsession != ''
  tags:
    - execution
    - desktop
    - mate
    - plymouth

- name: unitTest - Copied ubuntu-ucr-text.so to /usr/lib/{{ ansible_architecture }}-linux-gnu/plymouth.
  command: ls /usr/lib/{{ ansible_architecture }}-linux-gnu/plymouth
  register: result
  when: mate_xsession != ''
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth

- name: Update grub.
  command: update-grub
  register: result
  when: mate_xsession != ''
  tags:
    - execution
    - desktop
    - mate
    - plymouth

- name: unitTest - Updated grub.
  command: echo "{{ result }}"
  register: result
  when: mate_xsession != ''
  failed_when: "'vmlinuz' not in result.stdout"
  tags:
    - test
    - desktop
    - mate
    - plymouth
