---
- name: Download eduroam installer.
  get_url:
    url: https://ci.ucr.ac.cr/auri/instaladores/AURI-eduroam-UCR-Linux.tar.gz
    dest: "{{ wget_cache_path }}"
  tags:
    - execution
    - system
    - eduroam

- name: unitTest - Downloaded eduroam installer.
  command: ls {{ wget_cache_path }}
  register: result
  failed_when:  "'AURI-eduroam-UCR-Linux.tar.gz' not in result.stdout"
  tags:
    - execution
    - system
    - eduroam
