---
- name: Display Preprocess Part Message.
  debug:
    msg:
      - 'INFO: Preprocess information.'
  tags:
    - execution
    - fact
    - test

- name: Get non-root user running the play.
  local_action: command whoami
  register: user_on_host
  tags:
    - current
    - dconf
    - desktop
    - execution
    - fact
    - mate
    - packages
    - plymouth
    - test

- name: unitTest - Retrieved non-root user running the play.
  command: echo "{{ user_on_host }}"
  register: result
  failed_when: result.stdout == ''
  tags:
    - fact
    - test

- name: Verify if mate is installed and store the result.
  command: dpkg-query -l mate-desktop
  register: mate_xsession_result
  tags:
    - current
    - dconf
    - desktop
    - execution
    - fact
    - mate
    - packages
    - plymouth
    - test

- name: unitTest - Verified task 'mate is installed or not' executed sucessfully.
  command: echo "{{ mate_xsession_result.stderr }}"
  register: result
  failed_when: result.stdout != ''
  tags:
    - fact
    - test

- name: If mate-desktop installed, set mate_xsession = True.
  set_fact:
    mate_xsession: True
  when: "'MATE' in mate_xsession_result.stdout"
  tags:
    - current
    - dconf
    - desktop
    - execution
    - fact
    - mate
    - packages
    - plymouth
    - test

- name: If mate-desktop no installed, set mate_xsession = False.
  set_fact:
    mate_xsession: False
  when: mate_xsession is not defined
  tags:
    - current
    - dconf
    - desktop
    - execution
    - fact
    - mate
    - packages
    - plymouth
    - test

- name: unitTest - Set mate_xsession to True or False.
  command: echo "{{ mate_xsession }}"
  register: result
  failed_when: result.stdout != "True" and result.stdout != "False"
  tags:
    - fact
    - test

- import_tasks: repositories/main.yml
- import_tasks: packages/main.yml
- import_tasks: system/main.yml
- import_tasks: desktop/main.yml
