---
- name: Get the user running the play.
  local_action: command whoami
  register: user_on_host
  tags:
    - execution
    - test

- name: unitTest - Retrieved the user running the play.
  command: echo "{{ user_on_host }}"
  register: result
  failed_when: result.stdout == ''
  tags:
    - test

- name: Verify if mate is installed and store the result.
  command: bash -c "apt list --installed | grep mate-desktop"
  register: mate_xsession
  tags:
    - execution
    - test
    - packages
    - desktop
    - mate
    - plymouth

- import_tasks: repositories/main.yml
- import_tasks: packages/main.yml
- import_tasks: system/main.yml
- import_tasks: desktop/main.yml
