---
- name: Get non-root user running the play.
  local_action: command whoami
  register: user_on_host
  tags:
    - execution
    - test
    - current
    - fact

- name: unitTest - Retrieved non-root user running the play.
  command: echo "{{ user_on_host }}"
  register: result
  failed_when: result.stdout == ''
  tags:
    - test
    - fact

- name: Verify if mate is installed and store the result.
  command: echo "$(dpkg --get-selections | grep mate-desktop)"
  register: mate_xsession
  tags:
    - execution
    - test
    - packages
    - desktop
    - mate
    - plymouth
    - current
    - fact

- name: unitTest - Verified task 'mate is installed or not' executed sucessfully.
  command: echo "{{ mate_xsession.stderr }}"
  register: result
  failed_when: "result.stdout != ''"
  tags:
    - test
    - fact

- name: If mate-desktop installed, set mate_xsession = yes.
  command: echo 'yes'
  register: mate_xsession
  when: "'mate-desktop' in mate_xsession.stdout"
  tags:
    - execution
    - test
    - packages
    - desktop
    - mate
    - plymouth
    - current
    - fact

- name: If mate-desktop is not installed, set mate_xsession = no.
  command: echo 'no'
  register: mate_xsession
  when: "'mate-desktop' not in mate_xsession.stdout"
  tags:
    - execution
    - test
    - packages
    - desktop
    - mate
    - plymouth
    - current
    - fact

- name: unitTest - Set mate_xsession to yes or no.
  command: echo "{{ mate_xsession }}"
  register: result
  failed_when: "'yes' not in result.stdout and 'no' not in result.stdout"
  tags:
    - test
    - fact

- import_tasks: repositories/main.yml
- import_tasks: packages/main.yml
- import_tasks: system/main.yml
- import_tasks: desktop/main.yml
