---
- name: Enable unattended updates - distro.
  lineinfile:
    path: "{{ unattended_file_path }}"
    line: '        "${distro_id}:${distro_codename}";'
    insertafter: 'Unattended-Upgrade::Allowed-Origins {'
  tags:
    - execution
    - packages

- name: unitTest - enable unattended updates - distro.
  command: grep '"${distro_id}:${distro_codename}";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - test
    - packages

- name: Enable unattended updates - minimal steps.
  lineinfile:
    path: "{{ unattended_file_path }}"
    line: 'Unattended-Upgrade::MinimalSteps "true";'
    insertafter: '//Unattended-Upgrade::MinimalSteps "false";'
  tags:
    - execution
    - packages

- name: unitTest - enable unattended updates - minimal steps.
  command: grep 'Unattended-Upgrade::MinimalSteps "true";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - test
    - packages

- name: Enable unattended updates - unused dependencies.
  lineinfile:
    path: "{{ unattended_file_path }}"
    line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
    insertafter: '//Unattended-Upgrade::Remove-Unused-Dependencies "false";'
  tags:
    - execution
    - packages

- name: unitTest - enable unattended updates - unused dependencies.
  command: grep 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - test
    - packages
