---
- import_tasks: keys.yml

- name: Add repositories.
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ repositories }}"
  tags:
    - execution
    - repositories

- name: unitTest - Add repositories.
  command: grep '"${distro_id}:${distro_codename}";' {{ unattended_file_path }}
  register: result
  failed_when: result.stdout == ''
  tags:
    - test
    - repositories

- import_tasks: unattended.yml
