---
- name: Copy gnome configuration override (wallpaper, favorites, date format and input sources).
  copy:
    src: "{{ role_path }}/files/gschema/30_ucr-gnome-settings.gschema.override"
    dest: /usr/share/glib-2.0/schemas
  tags:
    - desktop
    - execution
    - gnome

- name: initTest - Copied gnome configuration override.
  command: ls /usr/share/glib-2.0/schemas
  register: result
  failed_when: "'30_ucr-gnome' not in result.stdout"
  tags:
    - desktop
    - gnome
    - test

- name: Copy wallpaper to /usr/share/backgrounds.
  copy:
    src: "{{ role_path }}/files/backgrounds/ubuntu-ucr-background.jpg"
    dest: /usr/share/backgrounds
  tags:
    - desktop
    - execution
    - gnome

- name: unitTest - Copied wallpaper to /usr/share/backgrounds.
  command: ls /usr/share/backgrounds
  register: result
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - desktop
    - gnome
    - test

- name: Compile gnome gsettings override.
  command: glib-compile-schemas /usr/share/glib-2.0/schemas
  tags:
    - desktop
    - execution
    - gnome

- name: unitTest - Compiled gnome gsettings override.
  command: gsettings list-recursively org.gnome.desktop.background
  register: result
  failed_when: "'ubuntu-ucr' not in result.stdout"
  tags:
    - desktop
    - gnome
    - test

- name: Reset gnome gsettings keys.
  command: bash -c 'gsettings list-schemas | xargs -n 1 gsettings reset-recursively'
  tags:
    - desktop
    - execution
    - gnome

- name: unitTest - Reset gnome gsettings keys.
  command: bash -c "gsettings list-schemas | grep 'org.gnome.desktop.interface'"
  register: result
  failed_when: result.stdout == ''
  tags:
    - desktop
    - gnome
    - test

- name: Display gui session restart warning.
  debug:
    msg:
      - 'WARNING: If a graphical user interface session is open, you must restart it.'
  tags:
    - desktop
    - execution
    - gnome
