---
- name: Create wget cache folder.
  file:
    path: "{{ wget_cache_path }}"
    state: directory
  tags:
    - execution
    - system

- name: unitTest - Created wget cache folder.
  command: ls {{ wget_cache_path }}
  register: result
  failed_when: result.stderr != ''
  tags:
    - test
    - system

- name: Disable apport.
  replace:
    path: /etc/default/apport
    regexp: 'enabled=1'
    replace: 'enabled=0'
  tags:
    - execution
    - system

- name: unitTest - Disable apport.
  command: cat /etc/default/apport
  register: result
  failed_when: "'enabled=1' in result.stdout"
  tags:
    - test
    - system

- import_tasks: eduroam.yml

- name: Set timezone to America/Costa_Rica.
  timezone:
    name: America/Costa_Rica
  tags:
    - execution
    - system

- name: unitTest - Setted timezone to America/Costa_Rica.
  command: ls -l /etc/localtime
  register: result
  failed_when: "'Costa_Rica' not in result.stdout"
  tags:
    - test
    - system

- import_tasks: office.yml
- import_tasks: signature.yml

- name: Enable terminal colors on /etc/skel/.bashrc.
  replace:
    path: "/etc/skel/.bashrc"
    regexp: "^#force_color_prompt=yes"
    replace: 'force_color_prompt=yes'
  tags:
    - execution
    - system
    - current

- name: Enabled terminal colors on /etc/skel/.bashrc.
  command: grep '#force_color_prompt=yes' /etc/skel/.bashrc
  register: result
  failed_when: result.stdout == '#force_color_prompt=yes'
  tags:
    - execution
    - system
    - current

- name: Enable terminal colors on ~/.bashrc.
  replace:
    path: ~/.bashrc
    regexp: "#force_color_prompt=yes"
    replace: 'force_color_prompt=yes'
  become: user_on_host
  tags:
    - execution
    - system
    - current

- name: Enabled terminal colors on ~/.bashrc.
  command: grep '#force_color_prompt=yes' ~/.bashrc
  register: result
  become: user_on_host
  failed_when: result.stdout == '#force_color_prompt=yes'
  tags:
    - execution
    - system
    - current
