---
- name: Download Libre office plugins.
  get_url:
    url: "{{ item }}"
    dest: "{{ wget_cache_path }}"
  loop: "{{ office_plugins }}"
  tags:
    - execution
    - office
    - system

- name: unitTest - Downloaded Libre office plugins.
  command: ls {{ wget_cache_path }}
  register: result
  failed_when: "'LanguageTool-stable.oxt' not in result.stdout"
  tags:
    - test
    - office
    - system

- name: Install Libre office plugins (gives ERROR but installs just FINE).
  # Extract the plugin name from the url and install it.
  command: bash -c 'NAME={{ item }} && NAME=$(printf -- "%s" "${NAME##*/}") && unopkg add -f --shared {{ wget_cache_path }}/$NAME'
  loop: "{{ office_plugins }}"
  # Give parse error on language tool but installs just fine.
  ignore_errors: yes
  tags:
    - execution
    - office
    - system

- name: unitTest - Installed Libre office plugins (giver ERROR, installs just FINE).
  command: unopkg list --shared
  register: result
  failed_when: "'org.openoffice.languagetool.oxt' not in result.stdout"
  ignore_errors: yes
  tags:
    - test
    - office
    - system
