---
- name: Download LanguageTool.
  get_url:
    url: https://www.languagetool.org/download/LanguageTool-stable.oxt
    dest: "{{ wget_cache_path }}"
  tags:
    - execution
    - system
    - office

- name: unitTest - Downloaded LanguageTool.
  command: ls {{ wget_cache_path }}
  register: result
  failed_when: "'LanguageTool-stable.oxt' not in result.stdout"
  tags:
    - test
    - system
    - office

- name: Install LanguageTool.
  command: unopkg add --shared {{ wget_cache_path }}/LanguageTool-stable.oxt
  tags:
    - execution
    - system
    - office
